### ISSUE TITLE
Trip counter reset

### ISSUE THREAD

**Issue by austeregrim** [inorton/EDMCJumpSpeed#1]
Can we get a button that allows me to reset the counters? 
Currently the only way to reset the counters is to restart EDMC. Would be neat to see an "overall" average, and a trip average, that we can reset the trip as needed. (Like a car, tracking entire mileage, but you have trip counters you can watch.)

Actually thinking about that, since EDSM knows my entire path traveled (I believe it's all in the journals) you could do a total LY's for the commander (be nicer if it could be per ship, but I don't know how that would be done.)

**Comment by inorton** [comment]
Trip counter reset? sure.

**Comment by inorton** [comment]
This was implemented, I have no idea when :)
