### ISSUE TITLE
python3 compatibility

### ISSUE THREAD

**Issue by alterNERDtive** [inorton/EDMCJumpSpeed#3]
EDMC is going to switch to Python 3.7 with its 3.5.0 release. No idea if this plugin is still maintained, but I’d like to be able to keep using it. I also kind of don’t wanna fork it and fix it myself ;)

**Comment by inorton** [comment]
Hiya, I will do a quick update!

**Comment by inorton** [comment]
If the plugin stops working after EDMC goes to py3 I will do a quick fix

**Comment by alterNERDtive** [comment]
No idea how exactly the plugin stuff works, but as far as I understand you’ll at least have to add a new startup method.
